//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_SW.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
