//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJ_SW.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Carts = new HashSet<Cart>();
            this.Credits = new HashSet<Credit>();
        }

        public int user_id { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [MinLength(3), MaxLength(14)]
        public string FName { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [MinLength(3), MaxLength(14)]
        public string LName { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [EmailAddress(ErrorMessage = "Enter Correct Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        [MinLength(3), MaxLength(14)]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "This Field Is Required")]
        public string City { get; set; }
        public Nullable<int> Login_Id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual Login Login { get; set; }
    }
}
